// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCache(arg1, arg2) {
  return window['go']['main']['App']['ClearCache'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ForceStop(arg1, arg2) {
  return window['go']['main']['App']['ForceStop'](arg1, arg2);
}

export function GetAdbStatus() {
  return window['go']['main']['App']['GetAdbStatus']();
}

export function GetCmdCwd() {
  return window['go']['main']['App']['GetCmdCwd']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetDevicesDetail() {
  return window['go']['main']['App']['GetDevicesDetail']();
}

export function GetRecentDevices() {
  return window['go']['main']['App']['GetRecentDevices']();
}

export function InstallAPK(arg1, arg2) {
  return window['go']['main']['App']['InstallAPK'](arg1, arg2);
}

export function InstallAdbLocal(arg1) {
  return window['go']['main']['App']['InstallAdbLocal'](arg1);
}

export function InstallAdbOnline() {
  return window['go']['main']['App']['InstallAdbOnline']();
}

export function IsLiveLogRunning() {
  return window['go']['main']['App']['IsLiveLogRunning']();
}

export function ListPackages(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListPackages'](arg1, arg2, arg3);
}

export function Pull(arg1, arg2, arg3) {
  return window['go']['main']['App']['Pull'](arg1, arg2, arg3);
}

export function Push(arg1, arg2, arg3) {
  return window['go']['main']['App']['Push'](arg1, arg2, arg3);
}

export function RecheckAdb() {
  return window['go']['main']['App']['RecheckAdb']();
}

export function RunCmd(arg1) {
  return window['go']['main']['App']['RunCmd'](arg1);
}

export function Screenshot(arg1, arg2) {
  return window['go']['main']['App']['Screenshot'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectZipFile() {
  return window['go']['main']['App']['SelectZipFile']();
}

export function StartApp(arg1, arg2) {
  return window['go']['main']['App']['StartApp'](arg1, arg2);
}

export function StartLiveLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartLiveLog'](arg1, arg2, arg3);
}

export function StartLogcat(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartLogcat'](arg1, arg2, arg3);
}

export function StopLiveLog() {
  return window['go']['main']['App']['StopLiveLog']();
}

export function StopLogcat() {
  return window['go']['main']['App']['StopLogcat']();
}

export function Uninstall(arg1, arg2) {
  return window['go']['main']['App']['Uninstall'](arg1, arg2);
}
