// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adb} from '../models';

export function ClearCache(arg1:string,arg2:string):Promise<string>;

export function Connect(arg1:string):Promise<string>;

export function Disconnect(arg1:string):Promise<string>;

export function ForceStop(arg1:string,arg2:string):Promise<string>;

export function GetAdbStatus():Promise<string>;

export function GetDevices():Promise<Array<adb.Device>>;

export function GetDevicesDetail():Promise<Array<adb.DeviceDetail>>;

export function InstallAPK(arg1:string,arg2:string):Promise<string>;

export function InstallAdbLocal(arg1:string):Promise<string>;

export function InstallAdbOnline():Promise<string>;

export function ListPackages(arg1:string,arg2:string,arg3:boolean):Promise<Array<string>>;

export function Pull(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Push(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RecheckAdb():Promise<string>;

export function Screenshot(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectZipFile():Promise<string>;

export function StartApp(arg1:string,arg2:string):Promise<string>;

export function StartLogcat(arg1:string,arg2:string):Promise<string>;

export function StopLogcat():Promise<void>;

export function Uninstall(arg1:string,arg2:string):Promise<string>;
